//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationsLib.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Vacation
    {
        [DataMember(Name = "VacationId", Order = 1)]
        public int VacationId { get; set; }
        public int EmployeeId { get; set; }
        [DataMember(Name = "StartDate", Order = 2)]
        public System.DateTime StartDate { get; set; }
        [DataMember(Name = "Duration", Order = 3)]
        public short Duration { get; set; }
        [DataMember(Name = "EndDate", Order = 4)]
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
